name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  built_value: ^8.2.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  flutter_easyloading: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/background-image-k24.jpg
